export const migration002 = {
  id: 2,
  name: 'pdv_sales_core',
  statements: [
    `CREATE TABLE IF NOT EXISTS vendas_locais (
      local_uuid TEXT PRIMARY KEY,
      servidor_id INTEGER,
      empresa_id INTEGER,
      loja_id INTEGER NOT NULL,
      caixa_id INTEGER NOT NULL,
      terminal_id TEXT,
      operador_id INTEGER,
      vendedor_id INTEGER NOT NULL,
      cliente_id_local TEXT,
      cliente_id_servidor INTEGER NOT NULL,
      numero_local TEXT NOT NULL,
      numero_documento TEXT NOT NULL,
      data_abertura TEXT NOT NULL,
      data_finalizacao TEXT,
      status TEXT NOT NULL,
      subtotal REAL NOT NULL DEFAULT 0,
      desconto_total REAL NOT NULL DEFAULT 0,
      acrescimo_total REAL NOT NULL DEFAULT 0,
      total REAL NOT NULL DEFAULT 0,
      quantidade_itens REAL NOT NULL DEFAULT 0,
      tipo_operacao TEXT NOT NULL DEFAULT 'VENDA',
      origem_operacao_uuid TEXT,
      status_fiscal TEXT NOT NULL DEFAULT 'NAO_GERADA',
      status_sincronizacao TEXT NOT NULL DEFAULT 'PENDENTE',
      tentativas_sincronizacao INTEGER NOT NULL DEFAULT 0,
      ultimo_erro TEXT,
      payload_json TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      sincronizado_em TEXT
    )`,
    `CREATE INDEX IF NOT EXISTS ix_vendas_locais_status
      ON vendas_locais(status, status_sincronizacao, created_at)`,
    `CREATE TABLE IF NOT EXISTS venda_itens_locais (
      local_uuid TEXT PRIMARY KEY,
      venda_uuid TEXT NOT NULL,
      produto_id INTEGER,
      sku_id INTEGER,
      ean13 TEXT,
      referencia TEXT,
      descricao TEXT NOT NULL,
      cor_id INTEGER,
      cor_descricao TEXT,
      tamanho_id INTEGER,
      tamanho_descricao TEXT,
      quantidade REAL NOT NULL,
      unidade TEXT,
      preco_tabela REAL NOT NULL DEFAULT 0,
      preco_unitario REAL NOT NULL DEFAULT 0,
      desconto_percentual REAL NOT NULL DEFAULT 0,
      desconto_valor REAL NOT NULL DEFAULT 0,
      acrescimo_valor REAL NOT NULL DEFAULT 0,
      total_item REAL NOT NULL DEFAULT 0,
      custo_referencia REAL NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'ATIVO',
      item_origem_uuid TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (venda_uuid) REFERENCES vendas_locais(local_uuid)
    )`,
    `CREATE INDEX IF NOT EXISTS ix_venda_itens_locais_venda
      ON venda_itens_locais(venda_uuid, status)`,
    `CREATE TABLE IF NOT EXISTS pagamentos_locais (
      local_uuid TEXT PRIMARY KEY,
      venda_uuid TEXT NOT NULL,
      forma_pagamento_id INTEGER,
      forma_pagamento_descricao TEXT NOT NULL,
      valor REAL NOT NULL,
      troco REAL NOT NULL DEFAULT 0,
      tipo_cartao TEXT,
      operadora_id INTEGER,
      bandeira_id INTEGER,
      nsu TEXT,
      codigo_autorizacao TEXT,
      quantidade_parcelas INTEGER NOT NULL DEFAULT 1,
      valor_parcela REAL NOT NULL DEFAULT 0,
      status TEXT NOT NULL DEFAULT 'CONFIRMADO',
      pagamento_origem_uuid TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (venda_uuid) REFERENCES vendas_locais(local_uuid)
    )`,
    `CREATE INDEX IF NOT EXISTS ix_pagamentos_locais_venda
      ON pagamentos_locais(venda_uuid, status)`,
    `CREATE TABLE IF NOT EXISTS descontos_locais (
      local_uuid TEXT PRIMARY KEY,
      venda_uuid TEXT NOT NULL,
      item_uuid TEXT,
      tipo TEXT NOT NULL,
      percentual REAL NOT NULL DEFAULT 0,
      valor REAL NOT NULL DEFAULT 0,
      motivo TEXT,
      usuario_solicitante_id INTEGER,
      usuario_autorizador_id INTEGER,
      data_autorizacao TEXT,
      created_at TEXT NOT NULL,
      FOREIGN KEY (venda_uuid) REFERENCES vendas_locais(local_uuid)
    )`,
    `CREATE TABLE IF NOT EXISTS operacoes_venda_locais (
      local_uuid TEXT PRIMARY KEY,
      tipo_operacao TEXT NOT NULL,
      venda_origem_uuid TEXT,
      venda_destino_uuid TEXT,
      motivo TEXT,
      usuario_id INTEGER,
      autorizador_id INTEGER,
      data_operacao TEXT NOT NULL,
      status_sincronizacao TEXT NOT NULL DEFAULT 'PENDENTE',
      created_at TEXT NOT NULL
    )`,
    `CREATE TABLE IF NOT EXISTS documentos_fiscais_locais (
      local_uuid TEXT PRIMARY KEY,
      venda_uuid TEXT NOT NULL,
      modelo TEXT NOT NULL DEFAULT '65',
      serie INTEGER,
      numero INTEGER,
      chave_acesso TEXT,
      tipo_emissao TEXT,
      ambiente TEXT,
      status TEXT NOT NULL DEFAULT 'NAO_GERADA',
      xml_path TEXT,
      danfe_path TEXT,
      protocolo TEXT,
      data_emissao TEXT,
      data_autorizacao TEXT,
      motivo_contingencia TEXT,
      tentativas_transmissao INTEGER NOT NULL DEFAULT 0,
      ultimo_erro TEXT,
      created_at TEXT NOT NULL,
      updated_at TEXT NOT NULL,
      FOREIGN KEY (venda_uuid) REFERENCES vendas_locais(local_uuid)
    )`,
    `CREATE INDEX IF NOT EXISTS ix_documentos_fiscais_locais_venda
      ON documentos_fiscais_locais(venda_uuid, status)`,
    `CREATE TABLE IF NOT EXISTS estoque_movimentos_locais (
      local_uuid TEXT PRIMARY KEY,
      sku_id INTEGER,
      tipo_movimento TEXT NOT NULL,
      quantidade REAL NOT NULL,
      saldo_anterior REAL NOT NULL DEFAULT 0,
      saldo_posterior REAL NOT NULL DEFAULT 0,
      venda_uuid TEXT,
      operacao_uuid TEXT,
      data TEXT NOT NULL,
      usuario_id INTEGER,
      terminal_id TEXT,
      status_sincronizacao TEXT NOT NULL DEFAULT 'PENDENTE',
      created_at TEXT NOT NULL
    )`,
    `CREATE INDEX IF NOT EXISTS ix_estoque_movimentos_locais_venda
      ON estoque_movimentos_locais(venda_uuid, sku_id)`
  ]
};
